[NoteDisplay]
# TapNoteAnimationIsNoteColor=0
# TapAdditionAnimationIsNoteColor=0
# HoldHeadAnimationIsNoteColor=0
HoldTopCapAnimationIsNoteColor=1
HoldBodyAnimationIsNoteColor=1
HoldBottomCapAnimationIsNoteColor=1
HoldTailAnimationIsNoteColor=1
# for some godforsaken reason hold tail note colour needs to be on