[NoteDisplay]
TapNoteAnimationIsNoteColor=0
# TapAdditionAnimationIsNoteColor=0
HoldHeadAnimationIsNoteColor=0
HoldTopCapAnimationIsNoteColor=0
HoldBodyAnimationIsNoteColor=0
HoldBottomCapAnimationIsNoteColor=0
HoldTailAnimationIsNoteColor=0